SITE_MAP = {
    "百度": "https://www.baidu.com",
    "哔哩哔哩": "https://www.bilibili.com",
    "b站": "https://www.bilibili.com",
    "bilibili": "https://www.bilibili.com",
    "知乎": "https://www.zhihu.com",
    "淘宝": "https://www.taobao.com",
    "京东": "https://www.jd.com",
    "微博": "https://www.weibo.com",
    "微信": "https://weixin.qq.com",
    "抖音": "https://www.douyin.com",
    "csdn": "https://www.csdn.net",
    "github": "https://github.com",
    "谷歌": "https://www.google.com",
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "gmail": "https://mail.google.com",
    "腾讯": "https://www.tencent.com",
    "阿里巴巴": "https://www.alibaba.com",
    "bing": "https://www.bing.com",
    "必应": "https://www.bing.com",
    "搜狗": "https://www.sogou.com",
    "360": "https://www.so.com",
    "163": "https://www.163.com",
    "网易": "https://www.163.com",
    "新浪": "https://www.sina.com.cn",
    "搜狐": "https://www.sohu.com",
    "qq": "https://www.qq.com",
    "腾讯qq": "https://www.qq.com",
    "百度云": "https://pan.baidu.com",
    "百度网盘": "https://pan.baidu.com",
    "阿里云": "https://www.aliyun.com",
    "腾讯云": "https://cloud.tencent.com",
}

BROWSER_ALIASES = {
    "edge": "edge",
    "微软": "edge",
    "chrome": "chrome",
    "谷歌": "chrome",
    "google chrome": "chrome",
    "firefox": "firefox",
    "火狐": "firefox",
    "ie": "ie",
    "ie浏览器": "ie",
}

APP_MAP = {
    "记事本": "notepad", "notepad": "notepad",
    "计算器": "calc", "calc": "calc",
    "画图": "mspaint", "mspaint": "mspaint",
    "命令提示符": "cmd", "cmd": "cmd", "命令行": "cmd",
    "任务管理器": "taskmgr", "taskmgr": "taskmgr",
    "控制面板": "control", "control": "control",
    "资源管理器": "explorer", "explorer": "explorer",
    "注册表": "regedit", "regedit": "regedit",
    "powershell": "powershell", "PowerShell": "powershell",
    "设置": "ms-settings:", "settings": "ms-settings:",
}
